### ISSUE TITLE
error on Readme.md on 'app/helpers/index.json.builder'

### ISSUE THREAD

**Issue by perecullera** [jhu-ep-coursera/fullstack-course3-module1-zips#2]
On Create Controller and View
whre it says:

> Fix the JSON view error by calling the helper method in app/helpers/index.json.builder.

it looks like it should say 

> app/viewa/zips/index.json.jbuilder

as there isn't any app/helpers/index.json.builder in the repo

**Comment by ejavaguy** [comment]
Thank you. We are sorry for the error and appreciate that you took the time to let us know. 

It has been corrected.
